<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\Networker.Extensions.MessagePack\Networker.Extensions.MessagePack.csproj" />
    <ProjectReference Include="..\..\Networker\Networker.csproj" />
  </ItemGroup>

</Project>
